SET(tutorial_libs ${EXAMPLES_DBO_LIBS})

#IF (WT_MULTI_THREADED)
#  SET(tutorial_libs ${tutorial_libs} ${BOOST_THREAD_LIB})
#ENDIF (WT_MULTI_THREADED)

ADD_EXECUTABLE(dbo-tutorial9 main.C Membership.C Organisation.C Person.C)
TARGET_LINK_LIBRARIES(dbo-tutorial9 ${tutorial_libs})

INCLUDE_DIRECTORIES(${WT_SOURCE_DIR}/src)

IF(MSVC)
  SET_TARGET_PROPERTIES(dbo-tutorial9 PROPERTIES FOLDER "dbo/examples")
ENDIF(MSVC)

IF(WT_INSTALL_EXAMPLES)
  INSTALL(TARGETS dbo-tutorial9 
    DESTINATION ${CMAKE_INSTALL_PREFIX}/${WT_EXAMPLES_DESTINATION}/feature/dbo/)
ENDIF(WT_INSTALL_EXAMPLES)
